package crac.enums;

import crac.module.matching.interfaces.ErrorStatus;

/**
 * This enum represent different error-codes
 * It also implements the ErrorStatus-Interface, a functional-interface that makes a SAM-implementation of the an existing error possible
 * @author David Hondl
 *
 */
public enum ErrorCode implements ErrorStatus{
	
	ACTION_NOT_VALID, ID_NOT_VALID, ID_NOT_FOUND, TASK_NOT_EXTENDABLE, PERMISSIONS_NOT_SUFFICIENT, ORGANISATIONAL_EXTENDS_SHIFT, 
	WORKABLE_EXTENDS_ORGANISATIONAL, WORKABLE_EXTENDS_WORKABLE, SHIFT_EXTENDS, CANNOT_CREATE, USER_NOT_PARTICIPATING, TASK_NOT_STARTED, TASK_NOT_READY, 
	TASK_NOT_JOINABLE, TASK_ALREADY_IN_PROCESS, CHILDREN_NOT_READY, UNDEFINED_ERROR, START_NOT_ALLOWED, NOT_COMPLETED_BY_USERS,
	QUANTITY_TOO_SMALL, QUANTITY_TOO_HIGH, QUANTITY_INCORRECT, DATASETS_ALREADY_EXISTS, JSON_READ_ERROR, JSON_MAP_ERROR, JSON_WRITE_ERROR, RESOURCE_UNCHANGEABLE, 
	TASK_IS_FULL, USERS_NOT_FRIENDS, WRONG_TYPE, ALREADY_FILLED, NOT_FOUND, TASK_HAS_OPEN_AMOUNT, CANNOT_BE_COPIED, EMPTY_DATA, STATE_NOT_AVAILABLE,
	NO_TOKEN, ALL_EVALS_TRIGGERED, ALREADY_ASSIGNED, WRONG_PARAMETER, NO_SUCH_STATE_FOUND, REQUIREMENTS_NOT_FULLFILLED, SUB_ITEMS_NOT_READY, FILE_NOT_FOUND, FILESIZE_TOO_BIG, 
	WRONG_REQUEST_METHOD, NO_SUCH_METHOD, NO_SUCH_TYPE, TASK_NOT_INTERACTABLE, STATE_NOT_ALLOWED, MIME_TYPE_NOT_ALLOWED, ELASTICSEARCH_NOT_AVAILABLE, UNSUPPORTED_MEDIA_TYPE;

	@Override
	public boolean hasError() {
		return true;
	}

}
